# Generated by Django 2.2.6 on 2019-12-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pass_chance',
            field=models.IntegerField(default=0),
        ),
    ]
