# Generated by Django 2.2.6 on 2019-12-07 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_pass_chance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pass_chance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pass_chance', to=settings.AUTH_USER_MODEL),
        ),
    ]
